### ISSUE TITLE
logs error

### ISSUE THREAD

**Issue by PQFitz** [wrfly/shadowbroker-auto#2]
Hi,Friend

IOError: [Errno 2] No such file or directory: 'C:\\Users\\Li\\Desktop\\shadowbroker-auto-master\\logs\\Eternalblue-2.2.0.exe-2017-04-21.17.39.50.665000-InConfig.validate.xml'

Need to manually create the logs directory,a Little bug

**Comment by wrfly** [comment]
Thanks bro.

```
    <t:parameter name="LogDir"
                 description="Absolute path of an Initial Log Directory"
                 type="String"
                 default="C:\Windows\Temp"/>
```

[That](https://github.com/wrfly/shadowbroker-auto/commit/aaa60de749feaade23c7f6e12527e1ed1eadf4ea) will makes you fell better.
